-----------------Data Analysis------------------
1. pandas ----------   Dataframe read and write operations
2. numpy  ----------    numerical python math operations
3. matplotlib ------     plots, graphs, visulization
4. seabron  --------     plots
5. plotly   -------      plots
6. bokhe     ------      plots

--------------------- Machine learning ------------------
7. sickit-learn (sklearn) ==== model devlopment
8. stats package          ==== linear regression

===================== Webscrapping and Database connection ========
9. sqlite           ======== sql connection
10. beautiful soup  ======== scrap the data
11. websocket       ======== scrap the data

====================== Deep learning ==================
12. Tensorflow        =====  deep learning models development
13. keras
14. pytorch           =====  develop by facebook(meta)
15. Opencv            =====  computer vision(reading and writing images)
16. Pillow            =====  reading images

======================== NLP ====================================
17. NLTK              =====  NATURAL language tool kit
18. spaCy             ====   NLP models
19. woedcloud         ====

======================= Web development - API ==============
20. Flask
21. Django
22. Fast API
23. Gradio

======================= Apps creation ===================
24. streamlit

======================= Transformers BERT ===============
25. TRANSFORMERS ==== huggingface (Google)

======================= DL:Pretrained models object detections =======
26. Vgg16
27. Mobilenet
28. Yolo   ------ Ultraytics

======================== NLP pretrined models===========
29.word2Vec -------- google
30.gloVe  ------------ standforuniversity

=====================
31. pickle
32. joblib

==================== GenAI LLM ========
33. Azure openai
34. google gemini
35. Amazon bedrock
36. LLAMA meta Ai
37. Langchain Framework

========== MODEL Deployment ===============
38. Mlflow

================= Cloud services ========= 
39. Azure mi related packages
40. GCP vertex ai packages
41. Amazon sagemaker Packages

=================== Alle NLP ======
42. Allen NLP packages

================== ML using pyspark ========
43. MLlib package

====
44. random
45. math
46. time
47. logger

**step-1: import packages**

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**step-2:create a DataFrame using List**

In [5]:
import pandas as pd
pd.DataFrame

pandas.core.frame.DataFrame

In [7]:
import pandas as pd
data=pd.DataFrame()
# we create a DataFrame
# but no data(no rows and coloums)
# we saved our dataframe with a name 'data'
data

Empty DataFrame
Columns: []
Index: []

**step-3: provide the data**

In [10]:
name=['Raj','Abhi','chinna']
pd.DataFrame(name)

0
0     Raj
1    Abhi
2  chinna

In [12]:
name=['Raj','Abhi','chinna']
age = [20,21,22]
pd.DataFrame( zip(name,age))

0   1
0     Raj  20
1    Abhi  21
2  chinna  22

In [14]:
name = ['Raj','Abhi','chinna']
age = [20,21,22]
city = ['pune','hyd','delhi']
pd.DataFrame( zip(name,age,city))

0   1      2
0     Raj  20   pune
1    Abhi  21    hyd
2  chinna  22  delhi

In [16]:
name = ['Raj','Abhi','chinna']
age = [20,21,22]
city = ['pune','hyd','delhi']
data=[name,age,city]
pd.DataFrame(data)

0     1       2
0   Raj  Abhi  chinna
1    20    21      22
2  pune   hyd   delhi

**step-4: provide the columns**
- columns we need to provide
- the number of columns
- here we have 3 coloumns

In [19]:
name = ['Raj','Abhi','chinna']
age = [20,21,22]
city = ['pune','hyd','delhi']
cols=['names','age','city']
df=pd.DataFrame( zip(name,age,city),
               columns=cols
               )
df

names  age   city
0     Raj   20   pune
1    Abhi   21    hyd
2  chinna   22  delhi

**step-5: provide the index**

In [25]:
name = ['Raj','Abhi','chinna']
age = [20,21,22]
city = ['pune','hyd','delhi']
cols=['names','age','city']
id=['a','b','c']
df=pd.DataFrame( zip(name,age,city),
               columns=cols,
                index=id
               )
df

names  age   city
a     Raj   20   pune
b    Abhi   21    hyd
c  chinna   22  delhi

**step-6: how to add a new column to already Existed dataframe**
- here we already has a data frame with name **df**
- it has 3 columns
- now we want add a new column **marks**
- we need to create a new array or list
- that length of list shouid equal to len of rows
- so here we have 3 rows, so new list also has 3 valued

In [28]:
#df['<new column name>']=<list>
marks=[100,200,300]
df['marks']=marks
df

names  age   city  marks
a     Raj   20   pune    100
b    Abhi   21    hyd    200
c  chinna   22  delhi    300

In [13]:
#name = ['Raj','Abhi','chinna']
#age = [20,21,22]
#city = ['pune','hyd','delhi']
#cols=['names','age','city']
#id=['a','b','c']
#df=pd.DataFrame( zip(name,age,city),
 #              columns=cols,
  #              index=id
 #              )
#df

**step-7:Create a DataFrame using an empty dataframe**

- In above case we created a list
- 
we create a dataframe by passing the list

In [23]:
#dataframe is created
df1=pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [25]:
name = ['Raj','Abhi','chinna']
age = [20,21,22]
city = ['pune','hyd','delhi']
df1['Name']=name
df1['Age']=age
df1['City']=city
df1

Name  Age   City
0     Raj   20   pune
1    Abhi   21    hyd
2  chinna   22  delhi

**step-8: Create a DataFrame Using Dictionary**

In [28]:
dict1={'Name':['raj','adhi','chinna'],
      'Age':[20,21,22],
      'city'  :['pune','hyd','delhi']}
dict1

{'Name': ['raj', 'adhi', 'chinna'],
 'Age': [20, 21, 22],
 'city': ['pune', 'hyd', 'delhi']}

In [32]:
df2=pd.DataFrame(dict1,index=['A','B','C'])
df2

Name  Age   city
A     raj   20   pune
B    adhi   21    hyd
C  chinna   22  delhi

- keys behave as columns
- values have as rows

In [47]:
dict1={'Name':'raj',
      'Age': 20,
      'city'  :'hyd'}
pd.DataFrame(dict1,index=[1])
# if using all scalar value 

Name  Age city
1  raj   20  hyd

- Data in the form of array
    - list : Normal Way
    - numpy : Numpy package
    - tensor : Tensorflow 

In [54]:
l1=[1,2,3]
import numpy as np
np.array(l1)

# tensor([1,2,3])

array([1, 2, 3])

In [56]:
l1=[1,2,3]
l2=[11,22,33]
l1+l2

[1, 2, 3, 11, 22, 33]

In [64]:
l1=[1,2,3]
a=np.array(l1)
l2=[11,12,13]
b=np.array(12)
a+b, a*b

(array([13, 14, 15]), array([12, 24, 36]))

**step-9: Drop the column**
- in order to drop a column we need to use **drop** method
- all the methods based on your dataframe name similar as string names
- it requires mainly 3 arguments
   - 1. column name
   - 2.  axis
       - axis=1 represents colums
       - axis=0 represents rows
   - 3. inplace
       - once you drop the column , the dataframe affected
       - the modified datafreme wants to save in a same name or different name
       - if you want to keep the same name then **inplace=True**

In [ ]:
df.drop()

In [74]:
# create the dataframe drop any column
name = ['Raj','Abhi','chinna']
age = [20,21,22]
city = ['pune','hyd','delhi']
cols=['names','age','city']
id=['A','B','C']
df=pd.DataFrame( zip(name,age,city),columns=cols,index=id)
df.drop('city',axis=1,inplace=True)
df

names  age
A     Raj   20
B    Abhi   21
C  chinna   22

In [78]:
# create the dataframe drop any column
name = ['Raj','Abhi','chinna']
age = [20,21,22]
city = ['pune','hyd','delhi']
cols=['names','age','city']
id=['A','B','C']
df=pd.DataFrame( zip(name,age,city),columns=cols,index=id)
df.drop('A',axis=0,inplace=True)
df

names  age   city
B    Abhi   21    hyd
C  chinna   22  delhi

In [ ]:
# create two dataframes df1 and df2
# add those dataframes
###### df1
names  age city
ramesh 20  hyd

####### df2
names  age city
ramesh 21  blr

ramesh  20 hyd
sureh   21 blr

append
concat
join

**step-10: How to qverwrite existed column data**
- we already has a dataframe
- now we want replace all the values of a specific column with new values
- first create a list with new values
- then update the column with new value, in the same way of how to create a new column
- df[new col]=data ,to create a new column
- df[old col]=new data,to to overwrite the old column

In [85]:
df['age']=[31,32]
df

names  age   city
B    Abhi   31    hyd
C  chinna   32  delhi

**step-11:how to save the DataFrame**

- we can save the dataframe using two ways
- CSV : comma seperated value
- excel
- for csv : .to_csv   extenction=.csv
- for excel: .to_excel  extenction=.xlsx

In [89]:
# create a dataframe
name = ['Raj','Abhi','chinna']
age = [20,21,22]
city = ['pune','hyd','delhi']
cols=['names','age','city']
id=['a','b','c']
df=pd.DataFrame( zip(name,age,city),columns=cols,index=id)
df

names  age   city
a     Raj   20   pune
b    Abhi   21    hyd
c  chinna   22  delhi

**csv format**

In [93]:
# dataframename.methodname
# where you want to save
# in what name you want to save
df.to_csv('data.csv')

**Excel sheet**

In [95]:
df.to_excel('data1.xlsx')

**step-12 : read the data**

- read_csv
- read_excel
- both avilable on pandas

In [98]:
pd.read_csv('data.csv')

Unnamed: 0   names  age   city
0          a     Raj   20   pune
1          b    Abhi   21    hyd
2          c  chinna   22  delhi

In [100]:
pd.read_excel('data1.xlsx')

Unnamed: 0   names  age   city
0          a     Raj   20   pune
1          b    Abhi   21    hyd
2          c  chinna   22  delhi

**step-13: how to avoid extra column**

- while we are saving the data, we have argument name **index**
- keep index=False

In [103]:
# give the different name, privide index= false
df.to_csv('data11.csv',index=False)
pd.read_csv('data11.csv')

names  age   city
0     Raj   20   pune
1    Abhi   21    hyd
2  chinna   22  delhi